version: '3'
services:
  eurekaservice:
      build:
        context: ./eureka
        dockerfile: eureka.dockerfile
      environment:
        EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaservice:8761/eureka
        EUREKA_INSTANCE_HOSTNAME: eurekaservice
        SERVER_ADDRESS: eurekaservice
      ports:
        - "8761:8761"
  zuul:
      build:
        context: ./zuul
        dockerfile: zuul.dockerfile
      environment:
        EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaservice:8761/eureka
        SPRING_CLOUD_CLIENT_IPADDRESS: zuul
#        EUREKA_INSTANCE_HOSTNAME: eurekaservice
        SERVER_ADDRESS: zuul
      links:
        - eurekaservice
      ports:
        - "18080:8080"
  user:
    build:
      context: ./user
      dockerfile: user.dockerfile
    links:
      - mysqldb
      - redisdb
      - eurekaservice
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/community
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaservice:8761/eureka
      SPRING_CLOUD_CLIENT_IPADDRESS: user
      SPRING_REDIS_HOST: redisdb
      SERVER_ADDRESS: user
    ports:
      - "8082:8080"
  community:
    build:
      context: ./community
      dockerfile: community.dockerfile
    links:
      - mysqldb
      - redisdb
      - eurekaservice
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/community
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaservice:8761/eureka
      SPRING_CLOUD_CLIENT_IPADDRESS: community
      SPRING_REDIS_HOST: redisdb
      SERVER_ADDRESS: community
    ports:
      - "8083:8080"
  role:
    build:
      context: ./role
      dockerfile: role.dockerfile
    links:
      - mysqldb
      - redisdb
      - eurekaservice
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/community
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaservice:8761/eureka
      SPRING_CLOUD_CLIENT_IPADDRESS: role
      SPRING_REDIS_HOST: redisdb
      SERVER_ADDRESS: role
    ports:
      - "8084:8080"
  property:
    build:
      context: ./property
      dockerfile: property.dockerfile
    links:
      - mysqldb
      - redisdb
      - eurekaservice
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/community
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaservice:8761/eureka
      SPRING_CLOUD_CLIENT_IPADDRESS: property
      SPRING_REDIS_HOST: redisdb
      SERVER_ADDRESS: property
    ports:
      - "8085:8080"
  redisdb:
    image: registry.docker-cn.com/library/redis:alpine
    ports:
      - "6379:6379"
  mysqldb:
    image: registry.docker-cn.com/library/mysql
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
