version: '3'
services:
  user:
    build:
      context: ./user
      dockerfile: user.dockerfile
    links:
      - mysqldb
      - redisdb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/community
      SPRING_REDIS_HOST: redisdb
      SERVER_ADDRESS: user
    ports:
      - "18080:8080"
  community:
    build:
      context: ./community
      dockerfile: community.dockerfile
    links:
      - user
      - mysqldb
      - redisdb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/community
      SPRING_REDIS_HOST: redisdb
      SERVER_ADDRESS: community
    ports:
      - "18081:8080"
  redisdb:
    image: registry.docker-cn.com/library/redis:alpine
    ports:
      - "6379:6379"
  mysqldb:
    image: registry.docker-cn.com/library/mysql
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password


