# Server settings (ServerProperties)
server:
  port: 8080
  address: localhost
  sessionTimeout: 30
  contextPath: /

  # Tomcat specifics
  tomcat:
    accessLogEnabled: false
    protocolHeader: x-forwarded-proto
    remoteIpHeader: x-forwarded-for
    basedir:
    backgroundProcessorDelay: 30 # secs

security:
  basic:
    enabled: false

spring:
  profile: test
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/community
    data: /**/data.sql
    username: root
    password: password
    useSSL: false
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop # here should be update, which is close to production configuration
  redis:
    database: 0
    host: localhost
    port: 6379
    pool:
      max-active: 100
      max-wait: -1
      max-idle: 20
      min-idle: 0
    timeout: 0
eureka:
  instance:
    hostname: ${spring.cloud.client.ipAddress}
    preferIpAddress:  false
    ipAddress: 127.0.0.1
    instance-id:  ${spring.cloud.client.ipAddress}:${server.port}
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone:  http://localhost:8761/eureka/