# Server settings (ServerProperties)
server:
  port: 8084
  address: localhost
  sessionTimeout: 30
  contextPath: /

  # Tomcat specifics
  tomcat:
    accessLogEnabled: false
    protocolHeader: x-forwarded-proto
    remoteIpHeader: x-forwarded-for
    basedir:
    backgroundProcessorDelay: 30 # secs

security:
  basic:
    enabled: false

spring:
  profiles: ci
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:community
    data: /**/data.sql
    username: root
    password: password
    useSSL: false
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    pool:
      max-active: 100
      max-wait: -1
      max-idle: 20
      min-idle: 0
    timeout: 0