# Server settings (ServerProperties)
server:
  port: 8080
  address: localhost
  sessionTimeout: 30
  contextPath: /

  # Tomcat specifics
  tomcat:
    accessLogEnabled: false
    protocolHeader: x-forwarded-proto
    remoteIpHeader: x-forwarded-for
    basedir:
    backgroundProcessorDelay: 30 # secs

security:
  basic:
    enabled: false

spring:
  cloud:
    client:
      ipAddress: 127.0.0.1
  application:
    name: role
  profiles:
    active: ci